application: fallingsandgpgpu
version: 1
runtime: python
api_version: 1

handlers:
- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /matrixMult\.html
  static_files: matrixMult.html
  upload: matrixMult.html

- url: /sylvesterText\.html
  static_files: sylvesterText.html
  upload: sylvesterText.html

- url: /static
  static_dir: static

